# Generated by Django 5.0.7 on 2024-07-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "คำตอบ", "verbose_name_plural": "คำตอบ"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "คำถาม", "verbose_name_plural": "คำถาม"},
        ),
    ]
